language: julia
os:
  - linux
  - windows
  - osx

julia:
  - 1.3
  # - nightly # commented to save energy and time

before_script:
  - git config --global user.name "GitUser"
  - git config --global user.email "git@us.er"

matrix:
  allow_failures:
  - julia: nightly

notifications:
  email:
    on_success: never
    on_failure: always
